### ISSUE TITLE
 Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by markusvankempen** [gandhimonik/DroneJS#3]
get this with mars mini drone when executing node basic-maneuver.js

{ flatTrimChanged: {} }
{ flatTrimChanged: {},
  flyingStateChanged: { state: 'takingoff' } }
../iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:242
            throw err;
            ^

TypeError: Cannot read property 'name' of undefined
    at MiniDroneController.parseData ...iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:254:21)

**Comment by gandhimonik** [comment]
I just added a feature of logging to help me fix the issues.

Can u update the library and try running the example "check-all-states.js" after turning on logging. Post all the logs here so I can check out your problem.

`
minidrone.logging(true);
`

Plz refer API for more details: https://github.com/gandhimonik/DroneJS#api`

**Comment by gandhimonik** [comment]
This is the example I am talking about.

https://github.com/gandhimonik/DroneJS#setup-navdata-stream

**Comment by markusvankempen** [comment]
Here you go 
Creating observer...
scanning devices...
peripheral discovered: Mars_101547 at promixity: 86
scanning stopped...
handshake completed...
proximity updated to: -41
services found: {"uuid":"9a66fa000800919111e4012d1540cb8e","name":null,"type":null,"includedServiceUuids":null},{"uuid":"9a66fb000800919111e4012d1540cb8e","name":null,"type":null,"includedServiceUuids":null},{"uuid":"9a66fd210800919111e4012d1540cb8e","name":null,"type":null,"includedServiceUuids":null},{"uuid":"9a66fd510800919111e4012d1540cb8e","name":null,"type":null,"includedServiceUuids":null},{"uuid":"9a66fe000800919111e4012d1540cb8e","name":null,"type":null,"includedServiceUuids":null}
characteristics found: {"uuid":"9a66fa000800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa010800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa020800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa030800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa040800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa050800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa060800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa070800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa080800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa090800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa0a0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa0b0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa0c0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa0d0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa0e0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa0f0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa100800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa110800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa120800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa130800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa140800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa150800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa160800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa170800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa180800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa190800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa1a0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa1b0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa1c0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa1d0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa1e0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]},{"uuid":"9a66fa1f0800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse"]}
characteristics found: {"uuid":"9a66fb000800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb010800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb020800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb030800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb040800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb050800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb060800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb070800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb080800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb090800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb0a0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb0b0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb0c0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb0d0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb0e0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb0f0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb100800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb110800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb120800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb130800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb140800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb150800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb160800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb170800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb180800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb190800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb1a0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb1b0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb1c0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb1d0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb1e0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]},{"uuid":"9a66fb1f0800919111e4012d1540cb8e","name":null,"type":null,"properties":["notify"]}
characteristics found: {"uuid":"9a66fd220800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write","notify"]},{"uuid":"9a66fd230800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write","notify"]},{"uuid":"9a66fd240800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write"]}
characteristics found: {"uuid":"9a66fd520800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write","notify"]},{"uuid":"9a66fd530800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write","notify"]},{"uuid":"9a66fd540800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write"]}
characteristics found: {"uuid":"9a66fe010800919111e4012d1540cb8e","name":null,"type":null,"properties":["writeWithoutResponse","write"]},{"uuid":"9a66fe020800919111e4012d1540cb8e","name":null,"type":null,"properties":["read","writeWithoutResponse","write","notify"]}
subscribed to characteristics...
subscribed to characteristics...
Creating observable...
Creating observable...
Drone connected successfully
Sending Command...
[ '4', '1', '0', '30', '0', '0', '0' ]
observable disposed
/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:242
            throw err;
            ^

TypeError: Cannot read property 'name' of undefined
    at MiniDroneController.parseData (/Users/mvankempen/iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:256:21)
    at SafeSubscriber._next (/Users/mvankempen/iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:181:34)
    at SafeSubscriber.__tryOrUnsub (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:185:22)
    at Subscriber._next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:89:18)
    at DistinctUntilChangedSubscriber._next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/operator/distinctUntilChanged.js:103:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:89:18)
    at Characteristic.<anonymous> (/Users/mvankempen/iot/minidrone/DroneJS/lib/services/MiniDroneService.js:238:34)
    at emitTwo (events.js:106:13)

**Comment by gandhimonik** [comment]
I have fixed this problem. Update the library and try it out.

Let me know if you face any other issues.

**Comment by markusvankempen** [comment]
Hi i still get some error and the logging does not seem to work.

            throw err;
            ^

TypeError: Cannot read property 'filter' of undefined
    at /Users/mvankempen/iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:320:47
    at Array.forEach (native)
    at MiniDroneController.getValuesByType (/Users/mvankempen/iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:279:18)
    at MiniDroneController.parseData (/Users/mvankempen/iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:267:33)
    at SafeSubscriber._next (/Users/mvankempen/iot/minidrone/DroneJS/lib/controllers/MiniDroneController.js:181:34)
    at SafeSubscriber.__tryOrUnsub (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:185:22)
    at Subscriber._next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/Subscriber.js:89:18)
    at DistinctUntilChangedSubscriber._next (/Users/mvankempen/iot/minidrone/DroneJS/node_modules/rxjs/operator/distinctUntilChanged.js:103:30)


and 

ENOENT: no such file or directory, open '/logs/dronejs_2017-07-03T14:23:15.940Z.log

**Comment by gandhimonik** [comment]
I have updated the logging mechanism to support generation of logs through files. Check out the function here.

`enableLogging([ dir ])`

**dir** - Optional. Directory to store the logs. If not specified then logs would get printed in the console.

The error you are getting about the logs is that the directory "logs" doesn't exist. Just create a directory and then specify the path of it or else just pass **null** to this function and it would print out logs in the console.

**Comment by markusvankempen** [comment]
Hello ... i still get the error 
node check-all-states.js
start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'logs/dronejs_2017-07-10T12:10:43.276Z.log'

**Comment by markusvankempen** [comment]
Ok logging works

**Comment by gandhimonik** [comment]
Hey,

Do you have any other issues or should I close this ticket?

**Comment by gandhimonik** [comment]
Hey,

I have resolved all the issues related to Cargo drone except the download problem. Plz check the updated version of the library and let me know if you have any other issues.
